name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations (use SQLite, no database service needed)
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test

  # Job for deployment (optional, example shown)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # Run deploy only if tests pass
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and run Docker container
      run: |
        docker build -t django-app .
        docker run -d -p 8000:8000 django-app
